import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


export default function Creator() {
  return (
    <>
      <Head>
        <title>Creator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div >
         About me
            <h6>
                text about me
            </h6>

        </div>
      </main>
    </>
  )
}
