import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.scss'
import Link from "next/link";
import {FormattedMessage, FormattedNumber, IntlProvider} from "react-intl";
import {useState} from "react";


const messages = {
    fr:{
        myMessage: "Aujourd'hui, c'est le {ts, date, ::yyyyMMdd}",
    },
    pl:{
        myMessage: "Dzisiaj jest {ts, date, ::yyyyMMdd}",
    },
    en:{
        myMessage:"Today is {ts, date, ::yyyyMMdd}"
    }

}


/*const messagesInPolish = {
    myMessage: "Dzisiaj jest {ts, date, ::yyyyMMdd}",
}*/
export default function Home() {
    const [lang,changeLeng]=useState("en")

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
            main first
            <button onClick={()=>changeLeng("fr")}>fr</button>
            <button onClick={()=>changeLeng("en")}>en</button>
            <button onClick={()=>changeLeng("pl")}>pl</button>
            <IntlProvider messages={messages[lang]} locale={lang}  defaultLocale="en">
                <p>
                    <FormattedMessage
                        id="myMessage"
                        defaultMessage="Today is {ts, date, ::yyyyMMdd}"
                        values={{ts: Date.now()}}
                    />
                    <br />
                  {/*  <FormattedNumber value={19} style="currency" currency="EUR" />*/}
                </p>
            </IntlProvider>

        </div>
      </main>
    </>
  )
}
